Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> print('''LET THE EXPERIMENT IS  OF TOSSING OF THREE COINS \n
REQUIRED FINITE SAMPLE IS = {HHH,HHT,HTH,HTT,THH,THT,TTH,TTT}= 8 \n
LEt OUR CHOISE TO FIND OUTCOMES OF ATLEAST TWO HEADS \n
THEN REQUIRED OUTCOMES IS= {HHH,HHT,HTH,THH }= 4 \n
LETS FIND OUT THE FREQUENCY OF COMING ATLEAST TWO HEAD =P(A)\n
THE FREQUENCY OF INTEPRETATION OF P(A) IS = REQUIRED OUTCOMES/TOTAL SAMPLE SPASE \n
THE FREQUENCY OF INTEPRETATION OF P(A) IS = 4/8 \n
P(A) IS = 0.5 ''')


LET THE EXPERIMENT IS  OF TOSSING OF THREE COINS 

REQUIRED FINITE SAMPLE IS = {HHH,HHT,HTH,HTT,THH,THT,TTH,TTT}= 8 

LEt OUR CHOISE TO FIND OUTCOMES OF ATLEAST TWO HEADS 

THEN REQUIRED OUTCOMES IS= {HHH,HHT,HTH,THH }= 4 

LETS FIND OUT THE FREQUENCY OF COMING ATLEAST TWO HEAD =P(A)

THE FREQUENCY OF INTEPRETATION OF P(A) IS = REQUIRED OUTCOMES/TOTAL SAMPLE SPASE 

THE FREQuency OF INTEPRETATION OF P(A) IS = 4/8 

P(A) IS = 0.5 
>>> 
